name: country
description: Query and retrieve country details by property type from a database of 250 countries.
version: 1.0.0
publish_to: none
homepage: https://github.com/p4-k4/country

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
