name: country
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  fpdart:
    path: /Users/paka/dev/fpdart

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
